### PR TITLE
Delete Nhost, not OSS

### PR DESCRIPTION
**Pull request by Miguelklappes**
NHost is **not** self hostable. They don't announce themselves as open source, nor they have any mention of it, not even guides.

### CODE REVIEW

**Comment by garrrikkotua** [comment]
@elitan, sorry for asking, but could you help us here? Is it possible to self-host Nhost? 
Thanks in advance :)

**Comment by elitan** [comment]
Good point. We should market ourselves more as open-source and have better guides around self-hosting!

But yea, Nhost's whole stack is open source:

- [Postgres](https://postgres.org/)
- [Hasura](https://github.com/hasura/graphql-engine)
- [Hasura Auth](https://github.com/nhost/hasura-auth)
- [Hasura Storage](https://github.com/nhost/hasura-storage)
- Serverless Functions (plan [Node.js](https://nodejs.org/))

You can self-host by:

1. Installing our CLI: `sudo curl -L https://raw.githubusercontent.com/nhost/cli/main/get.sh | bash
`

2. Start Nhost: `nhost`

**Comment by garrrikkotua** [comment]
Thank you @elitan!

@Miguelklappes I think we should keep Nhost :)

**Comment by garrrikkotua** [comment]
Closing for now - feel free to reopen if needed :)

**Comment by plmercereau** [comment]
It is also possible to run the Nhost stack with docker-compose:
https://github.com/nhost/nhost/tree/main/examples/docker-compose

**Pull request closed without merging**
