### PR TITLE
Add Zilliz

### PR DESCRIPTION
**Pull request by fzliu**
Zilliz is one company with two open source projects:
- [Towhee](https://github.com/towhee-io/towhee), an open source machine learning pipeline for generating embedding vectors
- [Milvus](https://github.com/milvus-io/milvus), an open source vector database for AI applications

### CODE REVIEW

**Comment by garrrikkotua** [comment]
@fzliu thanks for your PR!

Could you please change names of entry's a bit? Better if it would be "Zilliz's Towhee" and "Zilliz's Mivlus".

What do you think?

**Comment by garrrikkotua** [comment]
@fzliu I don't see you second commit

**Comment by fzliu** [comment]
I overwrite the reverted to the prior commit and then did a force-push. The changes are there.

image

**Comment by garrrikkotua** [comment]
@fzliu thanks!
Merging

**Pull request merged**
