### PR TITLE
add Gitlab to the list

### PR DESCRIPTION
**Pull request by sherwin-kwan**
Includes an image of the Gitlab logo - this can be used by any future contributors adding OSS hosted on Gitlab

### CODE REVIEW

**Comment by garrrikkotua** [comment]
Thanks for your PR!
Merged

**Comment by garrrikkotua** [comment]
@sherwin-kwan, sorry, I missed you added GitLab in this PR as well. 

We decided to add only private companies to this list (GitLab is a public one) - so I can't add it.

Happy to keep GitLab logo for Baserow :)

**Comment by garrrikkotua** [comment]
@sherwin-kwan, would you like to make another PR and add GitLab logo for Baserow? 

Otherwise, I can do it - just let me know :)

**Comment by sherwin-kwan** [comment]
Oh, I actually didn't even realize that GitLab had IPO'd already! It looked like an obvious omission, but that explains it.

I'll resubmit with just the GitLab logo for Baserow, thanks.

**Pull request merged**
