### PR TITLE
add: listmonk

### PR DESCRIPTION
**Pull request by kamikazechaser**
https://listmonk.app

### CODE REVIEW

**Comment by garrrikkotua** [comment]
Hey there, thanks for your PR!

We are welcome for all projects, but we aim to add only startups (for-profit companies) - otherwise we'll end up being another awesome-self-hosted :)

I didn't find any information on your website which confirms Listmonk is a company (like pricing / funding / about the company / etc). So right now I can't add Listmonk to the list. 

Thanks for understanding. Let me know if you have any questions :)

**Comment by kamikazechaser** [comment]
> Listmonk is a company

Makes sense, it is not a company on its own but rather a [FOSS product of Zerodha](https://www.producthunt.com/posts/listmonk-2)

**Comment by ssddanbrown** [comment]
@garrrikkotua Out of interest, what's the intention of the for-profit requirement? Seems to be quite a specific limiter amongst the wider scope of the "Awesome open-source alternatives to SaaS" title.

**Comment by garrrikkotua** [comment]
@ssddanbrown thanks for your question!

It was the original intention of the list - to showcase open-source startups that are making analogues of SaaS products. If we focus on all projects whether they are commercial or not, we may end up being another awesome-self-hosted :)

Regarding the title  - you are right, we should add some clarification there.

**Comment by ssddanbrown** [comment]
@garrrikkotua Fair enough, Thanks for the response!

**Pull request closed without merging**
