### PR TITLE
add peppermint

### PR DESCRIPTION
**Pull request by potts99**
Hope this is okay?

### CODE REVIEW

**Comment by garrrikkotua** [comment]
@potts99 thanks for your PR!

Could you please do two small changes? First, you should put the entry into the right place - so the categories are in alphabetical order. Second, please change the link in Peppermint (name of the company) to the website link, not the repo link.

Thanks :)

**Comment by potts99** [comment]
yeah no worries

**Comment by potts99** [comment]
Just pushed an update

**Comment by garrrikkotua** [comment]
Merged, thank you!

**Pull request merged**
