### PR TITLE
add gitpod as alternative to Codespaces

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
[`Gitpod`](https://gitpod.io/) automates the provisioning of ready-to-code development environments with the Support of multiple git providers & IDEs.

[Open in Gitpod](https://github.com/RunaCapital/awesome-oss-alternatives/pull/128)

### CODE REVIEW

**Comment by garrrikkotua** [comment]
@Siddhant-K-code thanks for your PR!

May I ask you to make description a bit shorter? Something like `Automated provisioning of development environments with multiple git providers & IDEs`

**Comment by Siddhant-K-code** [comment]
I have updated it ✨

**Comment by Siddhant-K-code** [comment]
I have updated it ✨

**Comment by garrrikkotua** [comment]
great, thank you!

Merging

**Pull request merged**
